; generated by PrusaSlicer 2.9.6 on 2024-01-01 at 00:00:00 UTC
M82 ; use absolute distances for extrusion
G92 E0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 X10 Y10 F7800
G1 X20 Y10 E1.0 F1800
G1 X20 Y20 E2.0
G1 E1.2 F2400
G92 E0
G1 X30 Y30 F7800
G1 E0.8 F2400
G1 X40 Y30 E1.6
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
G1 X10 Y10 E2.6
; filament used [mm] = 999.0
; estimated printing time (normal mode) = 1m 5s
